services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_ADMIN_USERNAME}
      POSTGRES_PASSWORD: ${DB_ADMIN_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

      DB_READONLY_USER: ${DB_READONLY_USER}
      DB_READONLY_PASSWORD: ${DB_READONLY_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
